name             'pv-monitoring'
maintainer       'Periscope Solutions'
maintainer_email 'dev@perisocpe-solutions.com'
license          'All rights reserved'
description      'Installs/Configures monitoring'
source_url       'https://git.mckinsey-solutions.com/infra/chef-ppv'
issues_url       'https://git.mckinsey-solutions.com/infra/chef-ppv/issues'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
source_url       'https://git.mckinsey-solutions.com/infra/chef-ppv'
issues_url       'https://git.mckinsey-solutions.com/infra/chef-ppv/issues'
version          '1.3.0'
