name             'db'
maintainer       'Periscope Solutions'
maintainer_email 'dev@periscope-solutions.com'
license          'All rights reserved'
description      'Installs/Configures db'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
source_url       'https://git.mckinsey-solutions.com/infra/chef-ppv'
issues_url       'https://git.mckinsey-solutions.com/infra/chef-ppv/issues'
version          '1.3.0'
depends          'database', '4.0.12'
depends          'common', '1.3.0'
