name             'pcas-admin-role'
maintainer       'Periscope Dev'
maintainer_email 'dev@periscope-solutions.com'
license          'All rights reserved'
description      'Installs/Configures pcas-admin-role'
long_description 'Installs/Configures pcas-admin-role'
source_url       'https://git.mckinsey-solutions.com/infra/periscope-environments'
issues_url       'https://git.mckinsey-solutions.com/infra/periscope-environments/issues'
version          '0.1.0'
depends 'pcas-admin-cookbook'
depends 'pcas-admin-assets-cookbook'
depends 'mash-splunk'
