default['ppt']['databag_item'] = 'pptsvc'
default['ppt']['component_name'] = 'ppt-service'
default['ppt']['app_port'] = '3000'
default['ppt']['log_directory'] = 'logs'
default['ppt']['chart_image_path'] = 'ppt/media/image2.png'
default['ppt']['appversions_databag_name'] = 'appversions'
default['ppt']['app_secrets'] = 'app-secrets'
default['ppt']['databag_name'] = 'smoke'
