name             'ppt'
maintainer       'Periscope Solutions'
maintainer_email 'dev@periscope-solutions.com'
license          'All rights reserved'
description      'Installs/Configures ppt'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
issues_url       'https://git.mckinsey-solutions.com/infra/chef-ppv/issues'
source_url       'https://git.mckinsey-solutions.com/infra/chef-ppv'
version          '1.1.0'
depends          'common', '1.3.0'
