lambda_policy_name        = "ndm-ppv-npn-autosleep-lambda"
lambda_role_name          = "ndm-ppv-npn-autosleep-lambda"
s3_rw_policy_name         = "autosleep-s3-rw-policy"
lambda_function_name      = "ndm-ppv-npn-autosleep"
lambda_env_var_tag_values = "tenant,solution,component"
s3_bucket_name            = "ndm-ppv-npn-autosleep"