AllCops:
  TargetRubyVersion: 2.0
ClassLength:
  Enabled: false
MethodLength:
  Enabled: false
SpaceBeforeFirstArg:
  AllowForAlignment: true
Style/TrailingCommaInArguments:
  Enabled: false
Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma
CyclomaticComplexity:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/LineLength:
  Max: 100
